### ISSUE TITLE
Questions: Applying classification model to 'treeshap' package..

### ISSUE THREAD

**Issue by dleotjd520** [ModelOriented/treeshap#12]
Hello?
I tried to apply treeSHAP to randomforest (RF) model of classification type in R program.
I made two RF models for classification with 'iris' data showing same result. 
In the steps, step with '**randomForest.unify**' function for two RF models showed errors. 
> unified.rf1 <- randomForest.unify(iris.rf1, train.data)
_Error in randomForest.unify(iris.rf1, train.data) : 
  Models built on data with categorical features are not supported - please encode them before training.

> unified.rf2 <- randomForest.unify(iris.rf2, train.x)
_Error in Prediction/n : 이항연산자에 수치가 아닌 인수입니다
(Translation: Binomial operator is an argument, not a number)

Error parts in 'randomForest.unify' function code are 
- ' if (any(attr(rf_model$terms, "dataClasses") != "numeric")) '  for iris.rf1'
- ' y[is.na(Feature), `:=`(Prediction, Prediction/n)] ' for iris.rf1' & iris.rf2

In this code, all classification models maybe showed same error in second part
because 'Prediction' of classification model was categorical variables. 
**How do I solve this problem?** 
(split the data by each class, and use class probability? I do not know in detail...) 
**Or Is there another way (or method) to run 'randomForest.unify' function for classification model?**

Thank you in advance.

Code i used is as follows:
##
library(randomForest)
data(iris)

set.seed(123)
sample.num<- sample(1:dim(iris)[1], dim(iris)[1]*0.7) # data spilt 
train.data <- iris[sample.num, ]
test.data  <- iris[-sample.num, ]

set.seed(123)
iris.rf1 <- randomForest(Species ~ ., data=train.data, ntree=100)

names(train.data)
train.x <- train.data[,-5]  # species column
train.y <- train.data[,5] # other columns

set.seed(123)
iris.rf2 <- randomForest(x =train.x, y= factor(train.y), ntree=100)

######## ERROR..
unified.rf1 <- randomForest.unify(iris.rf1 ,train.data)
unified.rf2 <- randomForest.unify(iris.rf2 ,train.x)

**Comment by krzyzinskim** [comment]
Bumping old issue. 

`randomForest.unify()` function should now (#30) work for binary classifiers that have a target that is a factor with levels 0 and 1. So for the example above, something like this will work:


```R
library(randomForest)
data(iris)

iris$Species <- as.factor(as.numeric(iris$Species == "setosa"))

set.seed(123)
sample.num<- sample(1:dim(iris)[1], dim(iris)[1]*0.7) # data spilt
train.data <- iris[sample.num, ]
test.data <- iris[-sample.num, ]
iris.rf <- randomForest(Species ~ ., data=train.data, ntree=100)

names(train.data)
train.x <- train.data[,-5] # select only predictors

unified.rf <- randomForest.unify(iris.rf, train.x) 
treeshap_results <- treeshap(unified.rf, train.x)
plot_feature_importance(treeshap_results)
```
