### ISSUE TITLE
treeshap ver. 1.0.0 goals

### ISSUE THREAD

**Issue by maksymiuks** [ModelOriented/treeshap#7]
Critical:

- [x] Rebuild `catboost.unify`, and make the function pass tests and evoke examples without an error
- [x] Rebuild `ranger.unify`, and make the function pass tests and evoke examples without an error
- [x] Prepare extensive tests for all unifiers 
- [x] Clean-up dependencies, remove unnecessary one
- [x] Interaction visualization 

Optional:

- [ ] Add experimental algorithm for tree shap O(TLD) comupatations
- [ ] Refresh README, prepare hex
- [x] Extend documentation
- [x] add rpart support
- [x] implement recalculate covers in C++
- [ ] make all unifiers work on DT 

Each goal should be solved as a separate issue.

**Comment by kapsner** [comment]
First of all, thx for this nice package!! Helps a lot to efficiently compute SHAP values, esp. for ranger in my case.

Is there a plan to bring this package also to CRAN (or maybe a slim version of it, including the wrappers for `ranger`and `gmb`, as `lightgbm` and `xgboost` packages already provide the computation of the SHAP values and plotting is already supported via `shapviz`)?
